import type { DriftGuardComparison, DriftGuardReport } from "../common/types.js";

declare const process: {
  argv: string[];
  env: Record<string, string | undefined>;
  exitCode?: number;
};

declare function require(name: string): any;

const fs = require("node:fs");

const COMMENT_MARKER = "<!-- driftguard:report -->";

interface GitHubComment {
  id: number;
  body?: string;
  user?: {
    type?: string;
  };
}

function formatPercent(value: number): string {
  return `${value.toFixed(1)}%`;
}

function shortSha(value: string | null): string {
  if (!value) {
    return "unknown";
  }
  return value.slice(0, 8);
}

function renderRegressionLine(item: DriftGuardComparison): string {
  const confidence = formatPercent(item.sprt.confidence * 100);
  const introduced = shortSha(item.change_point.introduced_at);
  return `- \`${item.function}()\` regressed P99 latency by ${formatPercent(item.p99_delta_percent)} - ${confidence} confidence - introduced in commit \`${introduced}\`.`;
}

export function renderComment(report: DriftGuardReport): string {
  const regressions = report.comparisons.filter((item) => item.is_regression);
  const lines: string[] = [
    COMMENT_MARKER,
    "## DriftGuard Performance Report",
    "",
    `Baseline \`${shortSha(report.baseline_commit)}\` vs candidate \`${shortSha(report.candidate_commit)}\`.`,
    "",
  ];

  if (regressions.length === 0) {
    lines.push("No statistically supported performance regressions detected.");
  } else {
    lines.push(...regressions.map(renderRegressionLine));
  }

  lines.push(
    "",
    "| Function | P99 delta | Samples | Quality | SPRT | Mann-Whitney p | Change point |",
    "| --- | ---: | ---: | --- | --- | ---: | --- |",
  );

  for (const item of report.comparisons) {
    const quality = item.quality.passed ? "pass" : "blocked";
    const samples = `${item.quality.baseline_count}/${item.quality.candidate_count}`;
    lines.push(
      `| \`${item.function}()\` | ${formatPercent(item.p99_delta_percent)} | ${samples} | ${quality} | ${item.sprt.decision} (${formatPercent(
        item.sprt.confidence * 100,
      )}) | ${item.mann_whitney.p_value.toFixed(4)} | \`${shortSha(item.change_point.introduced_at)}\` |`,
    );
  }

  const qualityWarnings = report.comparisons.flatMap((item) =>
    item.quality.warnings.map((warning) => `- \`${item.function}()\`: ${warning}`),
  );
  if (report.environment?.warnings.length) {
    qualityWarnings.push(...report.environment.warnings.map((warning) => `- environment: ${warning}`));
  }
  if (qualityWarnings.length) {
    lines.push("", "Quality warnings:", ...qualityWarnings);
  }

  lines.push("", "<sub>Generated by DriftGuard. Decisions use SPRT plus Mann-Whitney U, not a static threshold.</sub>");
  return lines.join("\n");
}

async function githubRequest<T>(method: string, path: string, token: string, body?: unknown): Promise<T> {
  const request: RequestInit = {
    method,
    headers: {
      "authorization": `Bearer ${token}`,
      "accept": "application/vnd.github+json",
      "content-type": "application/json",
      "x-github-api-version": "2022-11-28",
    },
  };
  if (body !== undefined) {
    request.body = JSON.stringify(body);
  }

  const response = await fetch(`https://api.github.com${path}`, request);

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub ${method} ${path} failed: ${response.status} ${text}`);
  }

  return (await response.json()) as T;
}

async function upsertGitHubComment(body: string): Promise<void> {
  const token = process.env.GITHUB_TOKEN;
  const repository = process.env.GITHUB_REPOSITORY;
  const issueNumber = process.env.PR_NUMBER || process.env.GITHUB_REF_NAME;

  if (!token || !repository || !issueNumber) {
    console.log(body);
    return;
  }

  const comments = await githubRequest<GitHubComment[]>(
    "GET",
    `/repos/${repository}/issues/${issueNumber}/comments?per_page=100`,
    token,
  );
  const existing = comments.find((comment) => comment.body?.includes(COMMENT_MARKER));

  if (existing) {
    await githubRequest<GitHubComment>("PATCH", `/repos/${repository}/issues/comments/${existing.id}`, token, { body });
    return;
  }

  await githubRequest<GitHubComment>("POST", `/repos/${repository}/issues/${issueNumber}/comments`, token, { body });
}

async function main(): Promise<void> {
  const input = process.argv[2] || "driftguard-report.json";
  const report = JSON.parse(fs.readFileSync(input, "utf8")) as DriftGuardReport;
  await upsertGitHubComment(renderComment(report));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
